-- This file was generated from supabase/seed/places.yaml
-- Do not edit this file directly. Instead:
-- 1. Edit the YAML file
-- 2. Run 'npm run seed' to regenerate this file

INSERT INTO public.places (id, name, latitude, longitude, osm_id, description)
VALUES
  (1, 'Cambridge Bay', 69.1169, -105.0593, NULL, 'Main research hub in Nunavut, home to the Canadian High Arctic Research Station'),
  (2, 'Université du Québec à Chicoutimi', 48.4197, -71.0538, NULL, 'Research partner institution with expertise in northern studies'),
  (3, 'Université Laval', 46.7817, -71.2747, NULL, 'Leading institution in Arctic research and host of Sentinel North program'),
  (4, 'Ottawa Shaw Centre', 45.4242529, -75.6912376, '264535169', 'Conference venue for Arctic research meetings'),
  (5, 'Permafrost impact on Aquatic Systems', 69.2342410666946, -105.99041660227468, NULL, 'Arctic is warming two to four times faster than any other place on the planet.  It can significantly affect permafrost, which is crucial to the region''s ground stability.  This study focuses on a river and lake-rich area located near Ikaluktutiak (Cambridge Bay, Nunavut).
Although little is known of permafrost conditions, local observations indicate that episodes  of abrupt and localized permafrost degradation have increased in the past decades. Therefore,  it represents a key site for studying and monitoring the effects of permafrost thaw on local  aquatic ecosystems and northern communities.
This project aims to detect past and recent indicators of degrading permafrost and assess  its impacts on aquatic ecosystems through remote sensing, geomorphology, and limnology.  More specifically, this project will focus on assessing the hydrological stability of lakes,  analyzing variations in lake surfaces over time, and mapping the geomorphological origins  and hydrological connectivity of these lakes.
The stable isotope composition of different water sources, including active-layer groundwater  and ground-ice was analysed to assess their contributions to sampled lakes and ponds. Our  preliminary results revealed diverse lake morphologies, ranging from shallow, flat lakes to  deeper lakes with variable bathymetric topography.
Permafrost cores (1.5 m) indicate high ground ice content with low amounts of organic matter.  Turbidity measurements in a tributary of Kitigaq River, where subsistence fishing occurs,  indicate above-normal turbidity values after the degradation of ice-rich permafrost. These  findings highlight the importance of monitoring permafrost degradation in this understudied  area since it has implications for both ecosystem health and local community.'),
  (6, 'Kitigaq Area Permafrost Degradation', 69.2319, -105.9444, NULL, 'Pr. Frédéric Bouchard team from University of Sherbrooke is looking to asses  permafrost degradation in the Kitigaq region, based on water sampling and  erosion modeling.'),
  (7, 'Campus Lavallée', 45.466043, -75.754984, '477197015', 'Research facility focusing on Arctic climate change.'),
  (8, 'Mahahual Mangrove Research', 18.7170436, -87.7114494, NULL, 'The research conducted in Mahahual, Mexico, highlights the rapid degradation  of the mangrove forest and its ecosystem. The main causes of degradation are: Urbanization, Deforestation Climate Change.');

-- Reset sequence
SELECT setval('places_id_seq', (SELECT MAX(id) FROM places), true);
